### ISSUE TITLE
5. Development Scripts (15 points) 🖊️

### ISSUE THREAD

**Issue by tetlisna** [DenWouk/eCommerce-Application#5]
1. (5 points) Create a script for running ESLint across the codebase, enabling quick and efficient identification of coding style issues and potential errors. [RSS-ECOMM-1_14](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint1/RSS-ECOMM-1_14.md) 🐞
2. (5 points) Create a script for running Prettier across the codebase, simplifying code formatting and ensuring uniform code style. [RSS-ECOMM-1_15](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint1/RSS-ECOMM-1_15.md) 🎨
3. (5 points) Create a script for running Jest tests, streamlining the process of executing tests and generating reports on test outcomes. [RSS-ECOMM-1_16](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint1/RSS-ECOMM-1_16.md) 🧾

**Comment by zakalupali89** [comment]
Done
